// Script to help initialize the backend
console.log('AppScreens Backend Initialization Script');
console.log('=====================================');
console.log('');
console.log('Please follow these steps to set up the backend:');
console.log('');
console.log('1. Make sure you have Node.js installed (version 14 or higher)');
console.log('2. Make sure you have MongoDB installed and running, or have access to a MongoDB Atlas cluster');
console.log('3. Install dependencies by running: npm install');
console.log('4. Update the .env file with your configuration:');
console.log('   - MONGODB_URI: Your MongoDB connection string');
console.log('   - JWT_SECRET: A secure secret for JWT tokens');
console.log('   - STRIPE_SECRET_KEY: Your Stripe secret key (for payments)');
console.log('5. Start the development server: npm run dev');
console.log('');
console.log('For Production Deployment:');
console.log('1. Update the .env.production file with your production configuration');
console.log('2. Build the frontend: npm run build (from the root directory)');
console.log('3. Set NODE_ENV=production');
console.log('4. Start the server: npm start');
console.log('OR');
console.log('1. Use Docker: docker-compose up -d');
console.log('');
console.log('The API will be available at http://localhost:5000');
console.log('');
console.log('API Endpoints:');
console.log('- POST /api/auth/register - Register a new user');
console.log('- POST /api/auth/login - Login user');
console.log('- GET /api/auth/profile - Get user profile (requires auth token)');
console.log('- POST /api/screenshots/download - Download app screenshots (requires auth token)');
console.log('- POST /api/screenshots/batch - Batch download screenshots (requires auth token and Starter plan)');
console.log('- POST /api/payments/checkout - Create a payment checkout session (requires auth token)');
console.log('- GET /api/payments/subscription - Get subscription details (requires auth token)');
console.log('- POST /api/users/profile - Update user profile (requires auth token)');
console.log('- GET /api/users/api-key - Get API key (requires auth token)');
console.log('- POST /api/users/api-key/regenerate - Regenerate API key (requires auth token)');